# conftest_template.py — copy this to your AutoGenerated Tests/ folder as conftest.py
# Provides the shared Appium driver fixture consumed by all page tests.
import pytest
from appium import webdriver
from appium.options import AppiumOptions


def pytest_addoption(parser):
    parser.addoption("--platform", default="android", choices=["android", "ios"],
                     help="Target platform")
    parser.addoption("--device-udid", required=True, help="Device UDID or ADB serial")
    parser.addoption("--app-path", default=None, help="Path to .apk/.ipa (Android or fresh iOS install)")
    parser.addoption("--bundle-id", default=None, help="Bundle ID for already-installed iOS app")
    parser.addoption("--appium-url", default="http://127.0.0.1:4723",
                     help="Appium server URL (default: http://127.0.0.1:4723)")


@pytest.fixture(scope="session")
def driver(request):
    platform = request.config.getoption("--platform")
    udid = request.config.getoption("--device-udid")
    app_path = request.config.getoption("--app-path")
    bundle_id = request.config.getoption("--bundle-id")
    appium_url = request.config.getoption("--appium-url")

    options = AppiumOptions()
    options.platform_name = platform.capitalize()
    options.udid = udid

    if platform == "android":
        options.automation_name = "UIAutomator2"
        if app_path:
            options.app = app_path
    else:
        options.automation_name = "XCUITest"
        if bundle_id:
            options.bundle_id = bundle_id
        elif app_path:
            options.app = app_path

    driver = webdriver.Remote(appium_url, options=options)
    driver.implicitly_wait(10)
    yield driver
    driver.quit()
