#!/usr/bin/env bash
# run_tests.sh — start Appium server and run a pytest suite.
# Usage:
#   ./run_tests.sh --platform android --udid emulator-5554 --suite AutoGenerated --project RealGreen
#   ./run_tests.sh --platform ios --udid <sim-udid> --suite "test-workflow" --project PestPac
set -euo pipefail

PLATFORM=""
UDID=""
SUITE="AutoGenerated Tests"
PROJECT=""
APPIUM_PORT=4723
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECTS_DIR="${OUTPUT_DIR:-$HOME/WWMobileTestAgentAIResults}"

usage() {
  echo "Usage: $0 --platform <android|ios> --udid <udid> --project <project> [--suite <suite>]"
  exit 1
}

while [[ $# -gt 0 ]]; do
  case $1 in
    --platform) PLATFORM="$2"; shift 2 ;;
    --udid)     UDID="$2"; shift 2 ;;
    --project)  PROJECT="$2"; shift 2 ;;
    --suite)    SUITE="$2"; shift 2 ;;
    *) usage ;;
  esac
done

[[ -z "$PLATFORM" || -z "$UDID" || -z "$PROJECT" ]] && usage

SUITE_DIR="$PROJECTS_DIR/$PROJECT/$SUITE"
if [[ ! -d "$SUITE_DIR" ]]; then
  echo "❌ Suite folder not found: $SUITE_DIR"
  exit 1
fi

# Start Appium in background if not already running
if ! curl -s "http://127.0.0.1:$APPIUM_PORT/status" > /dev/null 2>&1; then
  echo "▶️  Starting Appium server on port $APPIUM_PORT..."
  appium --port "$APPIUM_PORT" --log /tmp/appium.log &
  APPIUM_PID=$!
  sleep 3
  echo "   Appium PID: $APPIUM_PID"
else
  echo "✅ Appium already running on port $APPIUM_PORT"
  APPIUM_PID=""
fi

# Activate venv if available
VENV="$SUITE_DIR/.venv"
if [[ -d "$VENV" ]]; then
  source "$VENV/bin/activate"
elif [[ -d "$SCRIPT_DIR/.venv" ]]; then
  source "$SCRIPT_DIR/.venv/bin/activate"
fi

echo ""
echo "🧪 Running suite: $SUITE"
echo "   Project : $PROJECT"
echo "   Platform: $PLATFORM"
echo "   Device  : $UDID"
echo ""

cd "$SUITE_DIR"
pytest tests/ \
  --platform "$PLATFORM" \
  --device-udid "$UDID" \
  -v \
  --tb=short \
  --html="$PROJECTS_DIR/$PROJECT/reports/pytest_report_$(date +%Y-%m-%d_%H-%M).html" \
  --self-contained-html \
  2>&1 | tee "$PROJECTS_DIR/$PROJECT/reports/pytest_$(date +%Y-%m-%d_%H-%M).log" || true

# Stop Appium if we started it
if [[ -n "$APPIUM_PID" ]]; then
  echo ""
  echo "⏹  Stopping Appium (PID $APPIUM_PID)..."
  kill "$APPIUM_PID" 2>/dev/null || true
fi

echo ""
echo "✅ Done. Report saved to $PROJECTS_DIR/$PROJECT/reports/"
